version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform: x86
before_build:
  - nuget restore
build:
  project: /Calculator/Calculator.sln
  verbosity: minimal
test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\test.exe '
